// @ts-check

// 本项目以博客（blog/）为主，docs 仅用于支撑站内全文搜索，
// 因此采用自动生成的侧边栏即可，无需手工维护。
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
